/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;
import main.ListaAdyacencia;
import main.Grafo;

/**
 *
 * @author Valeria
 */
public class Ventana1 extends javax.swing.JFrame {

    /** Creates new form Ventana1 */
    
    ListaAdyacencia lista = new ListaAdyacencia();
    Grafo grafito = new Grafo();
    
    public Ventana1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fila = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        crearLaberinto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        columna = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        metodoLaberinto = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        mostrarLaberinto = new javax.swing.JTextArea();
        X = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("HACEDOR DE LABERINTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Dimensiones del laberinto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filaActionPerformed(evt);
            }
        });
        jPanel1.add(fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("X");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel4.setText("Columna");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("Fila");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        crearLaberinto.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        crearLaberinto.setText("Generar Laberinto");
        crearLaberinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearLaberintoActionPerformed(evt);
            }
        });
        jPanel1.add(crearLaberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Métodos de solución");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel10.setText("Selecciona un metodo de búsqueda de camino");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Solución del Laberinto");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        eliminar.setText("Eliminar Laberinto");
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, -1));

        columna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnaActionPerformed(evt);
            }
        });
        jPanel1.add(columna, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 80, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel12.setText("Insertar un número de columna y fila");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        metodoLaberinto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        metodoLaberinto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wall follower", "Depth First Search", "Breadth First Search" }));
        metodoLaberinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoLaberintoActionPerformed(evt);
            }
        });
        jPanel1.add(metodoLaberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 250, -1));

        mostrarLaberinto.setColumns(20);
        mostrarLaberinto.setRows(5);
        jScrollPane3.setViewportView(mostrarLaberinto);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 580, 260));
        jPanel1.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 160, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filaActionPerformed

    private void columnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnaActionPerformed
       // String columna = columna.getText();// TODO add your handling code here:
    }//GEN-LAST:event_columnaActionPerformed

    private void metodoLaberintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoLaberintoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodoLaberintoActionPerformed

    private void crearLaberintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearLaberintoActionPerformed
        int filita =Integer.parseInt(fila.getText());
        int columnita = Integer.parseInt(columna.getText());
        
        for(int i= 1; i<=columnita; i++){
            char y = (char) (65);
            char x = (char) (i+64);
            String nodito = Character.toString(y);
            grafito.NuevoNodo(nodito);
        
        mostrarLaberinto.setText(grafito.ImprimirGrafo());
        
       
        //columnita = 
       //Character.toString(Character.forDigit(i+65,10)
       
        //String n = Character.toString(Character.forDigit(columnita + 65, 10)); //Integer.toString(columnita);
        
        //for(int i = 0; i< columnita; i++){
            //grafito.NuevoNodo((char) i+65);
            //mostrarLaberinto.setText(grafito.ImprimirGrafo());
        }
        
        //int filita = Integer.parseInt(fila.getText());
        
        
        
        
    }//GEN-LAST:event_crearLaberintoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField columna;
    private javax.swing.JButton crearLaberinto;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> metodoLaberinto;
    private javax.swing.JTextArea mostrarLaberinto;
    // End of variables declaration//GEN-END:variables

}
